apiVersion: v1
kind: ReplicationController
metadata:
  name: vehicle-replica-set
spec:
  replicas: 5
  selector:
    app: vehicleappwithreplicaset
  template:
    metadata:
      name: vehicleappwithreplicaset
      labels:
        app: vehicleappwithreplicaset
    spec:
      containers:
        - name: vehicleappwithreplicasetcontainer
          image: toobamalaika/vehicles-today-app
          ports:
            - containerPort: 80
